apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080  # Port du service
      targetPort: 8080  # Port du conteneur backend
  type: NodePort
